# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPYS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=1)),
                ('rank1', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rank2', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rank3', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rank4', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rank5', models.DecimalField(decimal_places=1, max_digits=3)),
                ('rank6', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('gpys', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.GPYS')),
            ],
        ),
    ]
