# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpys',
            name='rank',
            field=models.CharField(max_length=5),
        ),
    ]
