# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20170604_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpys',
            old_name='rank1',
            new_name='bkzs',
        ),
        migrations.RenameField(
            model_name='gpys',
            old_name='rank2',
            new_name='ggzs',
        ),
        migrations.RenameField(
            model_name='gpys',
            old_name='rank',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='gpys',
            old_name='rank3',
            new_name='gsyy',
        ),
        migrations.RenameField(
            model_name='gpys',
            old_name='rank4',
            new_name='hybj',
        ),
        migrations.RenameField(
            model_name='gpys',
            old_name='rank5',
            new_name='jgdx',
        ),
        migrations.RenameField(
            model_name='gpys',
            old_name='rank6',
            new_name='xypc',
        ),
    ]
